import "FileExplorerSort.idl";

namespace NfqLib
{
    [default_interface]
    runtimeclass FileExplorerHelper
    {
        static Windows.Foundation.Collections.IVector<FileExplorerSort> GetSortColumns(String folderPath);
    }
}
