import "SortOrder.idl";

namespace NfqLib
{
    [default_interface]
    runtimeclass FileExplorerHelper
    {
        static Windows.Foundation.IAsyncOperation< Windows.Foundation.Collections.IVector<SortOrder> > GetSortColumnsAsync(String folderPath);
    }
}
