import "SortOrder.idl";

namespace NfqLib
{
    [default_interface]
    runtimeclass FileExplorerHelper
    {
        static Windows.Foundation.Collections.IVector<SortOrder> GetSortColumns(String folderPath);
    }
}
