namespace NfqLib
{
    [bindable]
    [default_interface]
    runtimeclass SortOrder 
    {
        SortOrder(String propertyKey, Boolean ascending);
        String PropertyKey{ get; };
        Boolean Ascending{ get; };
    }
}
