namespace NfqLib
{
    enum SortProperty
    {
        Name,
        Date,
        DateCreated,
        DateModified,
        DateTaken,
        Type,
        Size,
        Tags,
        Dimensions,
        Rating
    };

    enum SortDirection
    {
        Ascending,
        Descending
    };

    [bindable]
    [default_interface]
    runtimeclass SortOrder 
    {
        SortOrder(String propertyKey, Boolean isAscending);
        String PropertyKey{ get; };
        SortProperty Property{ get; };
        SortDirection Direction{ get; };
        Boolean IsAscending{ get; };
    }
}
