import "Win32FileSystemQueryOptions.idl";
import "Win32File.idl";
import "SortOrder.idl";

namespace NfqLib
{
    delegate void FileSystemChangedEventHandler();

    [bindable]
    [default_interface]
    runtimeclass Win32FileSystemQuery 
    {
        Win32FileSystemQuery(Win32FileSystemQueryOptions queryOptions);

        Win32FileSystemQueryOptions QueryOptions{ get; };

        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector< Win32File > > EnumerateAsync();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector< Win32File > > SortAsync(SortOrder sortOrder);

        event FileSystemChangedEventHandler FileSystemChanged;
    }
}
